import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import BaseLayout from "@/components/layouts/base-layout";
import {defaultLayoutStyles} from "@/styles/layout";
import GlobalStyle from "@/styles/global";
const inter = Inter({ subsets: ["latin"] });
import React from "react";
export const metadata: Metadata = {
  title: "JOAT.GG",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({
 children
}: RootLayoutProps) {
  return (
    <>
      <GlobalStyle />
      <html lang = "ko">
        <body className={inter.className}>
        <BaseLayout>{children}</BaseLayout>
        </body>
      </html>
    </>
  );
}
